server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boying?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

#MyBatis的mapper.xml的路径配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
